version: "3.7"

services:
  bot:
    image: feriancek/lemonbot:latest
    secrets:
      - apiToken
    deploy:
      labels: 
        - "traefik.enable=false"
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 10
secrets:
  apiToken:
    external: true
